Repository mdsreq-fga-unb/REQ-2025.2-T01-PPBM, pull requests merged in 2025-10, with the labels that each got.

#47 Feat: Add meeting Notes
  .DS_Store
  docs/astro.config.mjs
  docs/package.json
  docs/src/content/docs/atas/ata1.md
  docs/src/content/docs/atas/ata2.md
  docs/src/content/docs/atas/ata3.mdx
Labels: documentation, improvement

#52 refactor(cronograma, user-stories): atualização e reorganização das US
  docs/src/content/docs/visao/cronograma.md
  docs/src/content/docs/visao/user-stories.md
Labels: documentation

#53 Update README.md
  docs/README.md
Labels: documentation, improvement

#55 Adicionar backlog priorizado (MoSCoW + MVP) no GitPages
  docs/astro.config.mjs
  docs/src/content/docs/visao/backlog.md
Labels: documentation, improvement

#63 Atualização de Requisitos Funcionais e Não Funcionais, Histórias de Usuário e Matriz ICE/MoSCoW
  docs/astro.config.mjs
  docs/package-lock.json
  docs/src/content/docs/atas/ata3.md
  docs/src/content/docs/atas/ata5.md
  docs/src/content/docs/visao/backlog.md
  docs/src/content/docs/visao/objetivos.md
  docs/src/content/docs/visao/regras-negocio.md
  docs/src/content/docs/visao/requisitos.md
  docs/src/content/docs/visao/user-stories.md
Labels: documentation

#64 Ajustando o problema de build
  docs/src/content/docs/atas/ata5.md
Labels: bug, documentation
